export class PointService {
    //돈이 얼마 있는 지 검증
    // 서비스 안의 로직을 비지니스 로직이라 함!
    // 핵심
    checkValue() {
        console.log("현금이 있는 지 검증합니다.")
        // 1. 가진 돈 검증 코드 (대략 10줄)
        // ...
        // ...
        // ...
        // ...
    }
}