version: "3.7"

services:
  my-backend: 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/myfolder/
    ports:
      - 3000:3000


  my-database:
    image: mongo:latest
    ports:
      - 27017:27017
